### PR TITLE
feat: Build ARM compatible docker image

### PR DESCRIPTION
**Pull request by lusu007**
Implements #27

### CODE REVIEW

**Comment by varun-raj** [comment]
@lusu007 Possible to resolve the conflict? We'can goahead with this once resolved

**Comment by lusu007** [comment]
Done @varun-raj!

It's possible that this needs a follow-up PR because I can't properly test this workflow with this repository.
However, the configuration I use works with another repository without any issues.

**Comment by sai80082** [comment]
@lusu007, I tried your workflow but couldn't get it to run successfully. It seems that `build-args` doesn't accept lists (refer to [this comment](https://github.com/docker/build-push-action/issues/557#issuecomment-1435418795) for more details).

To test the workflow, try pushing it to your main branch since it only runs when it's on the main branch.

**Comment by TeChn4K** [comment]
The Dockerfile does not use any `ARG` at all, so `build-args` seem pretty useless.

**Comment by lusu007** [comment]
> @lusu007, I tried your workflow but couldn't get it to run successfully. It seems that `build-args` doesn't accept lists (refer to [this comment](https://github.com/docker/build-push-action/issues/557#issuecomment-1435418795) for more details).
> 
> To test the workflow, try pushing it to your main branch since it only runs when it's on the main branch.

I pushed a potential fix but do not have any time to test it, I will do it later today or tomorrow.

**Comment by lusu007** [comment]
> @lusu007, I tried your workflow but couldn't get it to run successfully. It seems that `build-args` doesn't accept lists (refer to [this comment](https://github.com/docker/build-push-action/issues/557#issuecomment-1435418795) for more details).
> 
> To test the workflow, try pushing it to your main branch since it only runs when it's on the main branch.

Sorry to bother you @sai80082. Is it possible for you to test the action again?
I'm currently not able to get the release job running in my forked repo. (see: https://github.com/lusu007/immich-power-tools/actions/runs/12057234712/job/33621410557)

**Comment by sai80082** [comment]
Sure @lusu007. The issue is that the release workflow is running on forked repositories as well, which causes the build to fail. I'll work on creating a new workflow to ensure it functions correctly for both the original and forked repositories.

**Pull request merged**
